# Main Window
TITLE = "Modatron3000"
WINDOW_SIZE_WIDTH = 850
WINDOW_SIZE_HEIGHT = 600

TITLE_FONT_SIZE = 32
LABEL_FONT_SIZE = 16

GENERAL_LABEL_TEXT = "General"

#General mod info
MOD_DIRECTORY = "null"
MOD_DESCRIPTOR_DIR = "null"
MOD_DESCRIPTOR = []
MOD_VERSION = "null"
HISTORY_DIRECTORY = "null"
COMMON_DIRECTORY = "null"

COUNTRY_DICTIONARY = {}

COUNTRY_LABEL_TEXT = "Countries"
NEW_COUNTRY_BUTTON_TEXT = "New Country"
COUNTRY_CONTAINER_NAME = "country_container"